### ISSUE TITLE
error "local variable 'label' referenced before assignment" shows if vis=True 

### ISSUE THREAD

**Issue by zzks** [chenyilun95/tf-cpn#30]
set vis=True 
run python mptest.py -d 0-1 -r 350
the follow error shows:

05-29 15:47:43 Current epoch is 350.
ran 0s >> << left 0s
Process Worker-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/media/projects/tf-cpn2/models/COCO.res101.384x288.CPN/../../lib/tfflat/mp_utils.py", line 34, in run
    msg = self._func(self.id, *self.args, **self.kwargs)
  File "/media/projects/tf-cpn2/models/COCO.res101.384x288.CPN/mptest.py", line 220, in func
    return test_net(tester, logger, dets, range)
  File "/media/projects/tf-cpn2/models/COCO.res101.384x288.CPN/mptest.py", line 90, in test_net
    test_img, detail = Preprocessing(test_data[i], stage='test')
  File "/media/projects/tf-cpn2/models/COCO.res101.384x288.CPN/dataset.py", line 241, in Preprocessing
    draw_skeleton(tmpimg, label.astype(int))
UnboundLocalError: local variable 'label' referenced before assignment

**Comment by hustcc19860606** [comment]
Do you know how to deal with this problem? @zzks
