### ISSUE TITLE
ImportError: dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by tianjiahao** [chenyilun95/tf-cpn#59]
myubuntu:~/Desktop/tf-cpn/models/COCO.res101.384x288.CPN$ python3 mptest.py -d 0 -m log/model_dump/snapshot_350.ckpt
Traceback (most recent call last):
  File "mptest.py", line 21, in <module>
    from COCOAllJoints import COCOJoints
  File "/home/myubuntu/Desktop/tf-cpn/models/COCO.res101.384x288.CPN/../../data/COCO/COCOAllJoints.py", line 12, in <module>
    from pycocotools.coco import COCO
  File "/home/myubuntu/anaconda3/lib/python3.6/site-packages/pycocotools-2.0-py3.6-linux-x86_64.egg/pycocotools/coco.py", line 49, in <module>
    import matplotlib.pyplot as plt
  File "/home/myubuntu/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 113, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/home/myubuntu/anaconda3/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 60, in pylab_setup
    [backend_name], 0)
  File "/home/myubuntu/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 16, in <module>
    from .backend_qt5 import (
  File "/home/myubuntu/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 18, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/home/myubuntu/anaconda3/lib/python3.6/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 20, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "/home/myubuntu/anaconda3/lib/python3.6/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 56, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "/home/myubuntu/anaconda3/lib/python3.6/site-packages/matplotlib/backends/qt_compat.py", line 137, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: dlopen: cannot load any more object with static TLS

anyone know how to resolve this error,and which version of tensorflow is suitable?
my computer:
ubuntu14.04, tensorflow-gpu1.2.0, cuda8.0, cudnn5.1

**Comment by xinming31** [comment]
hi, do you fix it? I have the same problem. How do you fix it ,plz?
